# Generated by Django 3.0.6 on 2020-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='terms_conditions',
        ),
        migrations.AddField(
            model_name='student_info',
            name='phone',
            field=models.CharField(default='98--------', max_length=10),
        ),
    ]
