# Generated by Django 3.0.6 on 2020-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='sub_semester',
            new_name='subject_semester',
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(default='Compulsory', max_length=12),
        ),
    ]
