# Generated by Django 3.0.6 on 2020-06-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200614_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], default='Compulsory', max_length=12),
        ),
    ]
