# Generated by Django 3.0.6 on 2020-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200614_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=7),
        ),
    ]
